import assert from "node:assert/strict";
import test from "node:test";
import { spawn } from "node:child_process";
import fs from "node:fs";
import net from "node:net";
import os from "node:os";
import path from "node:path";
import { io, type Socket } from "socket.io-client";
import type { GameAck, PartyGameSnapshot, QuizSnapshot, User } from "@lumio/shared";
import { quizQuestions } from "./quizQuestions.js";

test("Quiz real authenticated sockets: observer privacy, answered reconnect, chat isolation and early reveal", { timeout: 60000 }, async (context) => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "lumio-quiz-socket-"));
  const port = await new Promise<number>((resolve) => { const server = net.createServer(); server.listen(0, "127.0.0.1", () => { const address = server.address() as net.AddressInfo; server.close(() => resolve(address.port)); }); });
  const outbox = path.join(directory, "mail.jsonl"), origin = "http://127.0.0.1:5173";
  const child = spawn(process.execPath, ["--import", "tsx", "src/index.ts"], { cwd: process.cwd(), env: { ...process.env, PORT: String(port), NODE_ENV: "development", PERSISTENCE_MODE: "file", AUTH_STORE_FILE: path.join(directory, "auth.json"), EMAIL_PROVIDER: "dev-file", EMAIL_DEV_OUTBOX_FILE: outbox, APP_PUBLIC_URL: origin, CLIENT_ORIGIN: origin, GOOGLE_CLIENT_ID: "", GOOGLE_CLIENT_SECRET: "", GOOGLE_TOKEN_ENCRYPTION_KEY: "", YOUTUBE_API_KEY: "" }, stdio: "ignore" });
  const sockets: Socket[] = [];
  context.after(async () => { sockets.forEach((s) => s.disconnect()); child.kill(); await Promise.race([new Promise((resolve) => child.once("exit", resolve)), new Promise((resolve) => setTimeout(resolve, 2000))]); fs.rmSync(directory, { recursive: true, force: true }); });
  const api = `http://127.0.0.1:${port}`;
  const until = async (predicate: () => boolean | Promise<boolean>) => { for (let i = 0; i < 150; i++) { if (await predicate()) return; await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("Quiz socket condition timed out"); };
  await until(async () => { try { return (await fetch(api + "/api/health")).ok; } catch { return false; } });
  const request = (route: string, token?: string, body?: unknown) => fetch(api + route, { method: "POST", headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(body ? { "Content-Type": "application/json" } : {}) }, body: body ? JSON.stringify(body) : undefined });
  const sessions: { token: string; user: User }[] = [];
  for (const displayName of ["Quiz Socket A", "Quiz Socket B", "Quiz Observer C"]) {
    const email = `${displayName.replaceAll(" ", "")}@example.test`, password = "local-quiz-test-123";
    assert.equal((await request("/api/auth/signup", undefined, { displayName, email, password })).status, 201);
    const link = JSON.parse(fs.readFileSync(outbox, "utf8").trim().split("\n").at(-1)!).text.match(/https?:\/\/\S+/)[0];
    assert.equal((await request("/api/auth/verification/confirm", undefined, { token: new URL(link).hash.slice(7) })).status, 204);
    sessions.push(await (await request("/api/auth/login", undefined, { email, password })).json());
  }
  const { house } = await (await request("/api/houses", sessions[0].token, { name: "Quiz sockets QA" })).json();
  const { invite } = await (await request(`/api/houses/${house.id}/invites`, sessions[0].token, { maxUses: 3, expiresInHours: 1 })).json();
  for (const session of sessions.slice(1)) assert.equal((await request(`/api/invites/${invite.token}/accept`, session.token)).status, 200);
  const states: (QuizSnapshot | null)[] = [null, null, null], traffic: unknown[][] = [[], [], []], chats: unknown[][] = [[], [], []];
  const connect = async (index: number) => {
    const socket = io(api, { transports: ["websocket"], auth: { token: sessions[index].token }, extraHeaders: { Origin: origin } }); sockets[index] = socket;
    socket.on("game:snapshot", (s: PartyGameSnapshot | null) => { if (!s || s.gameType === "quiz") states[index] = s; traffic[index].push(s); });
    socket.on("game:state", (s) => traffic[index].push(s)); socket.on("chat:message", (s) => chats[index].push(s));
    await until(() => socket.connected);
    const joined = new Promise<void>((resolve) => socket.once("room:snapshot", () => resolve()));
    socket.emit("room:join", { roomId: house.primaryRoomId, user: sessions[index].user }); await joined;
  };
  for (let i = 0; i < 3; i++) await connect(i);
  const send = async (index: number, type: string, extra: object = {}) => {
    const s = states[index]; return await sockets[index].timeout(3000).emitWithAck("game:action", { gameType: "quiz", type, roomId: house.primaryRoomId, ...(type === "open" ? {} : { sessionId: s!.sessionId, roundId: s!.roundId, revision: s!.revision }), ...extra }) as GameAck;
  };
  assert.ok((await send(0, "open")).ok); await until(() => states.every(Boolean));
  assert.ok((await send(0, "join")).ok); assert.ok((await send(1, "join")).ok);
  assert.equal((await send(2, "start")).ok, false); assert.ok((await send(0, "start")).ok);
  await until(() => states.every((s) => s?.phase === "QUESTION"));
  const question = quizQuestions.find((q) => q.prompt === states[0]!.question!.prompt)!;
  const correct = states[0]!.question!.answers.indexOf(question.answers[question.correctIndex]);
  assert.deepEqual(states[0]!.question, states[2]!.question); assert.equal((await send(2, "answer", { option: correct })).ok, false);
  assert.equal((await send(2, "join")).ok, false);
  assert.equal((await send(1, "answer", { option: correct, score: 999 })).ok, false);
  assert.ok((await send(1, "answer", { option: correct })).ok);
  await until(() => states[1]?.ownAnswer === correct); sockets[1].disconnect(); await connect(1);
  assert.ok((await send(1, "open")).ok); await until(() => states[1]?.ownAnswer === correct);
  assert.equal(states[1]!.phase, "QUESTION"); assert.equal((await send(1, "answer", { option: (correct + 1) % 4 })).ok, false);
  assert.equal(states[0]!.ownAnswer, undefined); assert.equal(states[2]!.ownAnswer, undefined);
  for (const messages of traffic) assert.doesNotMatch(JSON.stringify(messages), /correctAnswer|correctIndex|ownCorrect|ownPoints|distribution|explanation|deck/);
  for (const s of states) assert.ok(s!.players.every((p) => p.score === 0));
  assert.deepEqual(chats, [[], [], []], "Quiz answer is never routed through Party Chat");
  sockets[2].emit("chat:message", { roomId: house.primaryRoomId, body: "Observando o Quiz" }); await until(() => chats[0].length === 1);
  assert.ok((await send(0, "answer", { option: correct })).ok);
  await until(() => states.every((s) => s?.phase === "REVEAL"));
  assert.equal(states[2]!.reveal!.correctIndex, correct); assert.equal(states[2]!.reveal!.distribution[correct], 2);
  assert.equal(states[2]!.reveal!.ownPoints, 0); assert.equal(states[2]!.eligibleCount, 2);
  assert.ok(states[0]!.endsAt - states[0]!.startedAt === 6000);
});
