import { z } from "zod";
export const questionSchema = z.object({
  id: z.string().min(1), category: z.enum(["science", "math"]), difficulty: z.enum(["easy", "medium", "hard"]),
  prompt: z.string().min(1), answers: z.tuple([z.string().min(1), z.string().min(1), z.string().min(1), z.string().min(1)]), correctIndex: z.number().int().min(0).max(3),
}).strict();
export type QuizQuestion = z.infer<typeof questionSchema>;
// Authored locally for Lumio. Correct answer first only in the private source;
// the runtime shuffles the same four alternatives once for all viewers.
const groups: { category: QuizQuestion["category"]; difficulty: QuizQuestion["difficulty"]; rows: string[] }[] = [
  { category: "science", difficulty: "easy", rows: [
    "Qual estrela está no centro do Sistema Solar?|Sol|Sírius|Vega|Polaris",
    "Qual planeta é conhecido como Planeta Vermelho?|Marte|Vênus|Júpiter|Netuno",
    "Que gás do ar usamos na respiração celular aeróbica?|Oxigênio|Hélio|Neônio|Argônio",
    "Qual órgão bombeia sangue pelo corpo humano?|Coração|Estômago|Pulmão|Rim",
    "Qual estado físico tem forma e volume definidos?|Sólido|Líquido|Gasoso|Plasma",
    "Qual destes animais é um mamífero?|Golfinho|Tubarão|Sardinha|Polvo",
    "Qual parte da planta absorve água do solo?|Raiz|Flor|Fruto|Pétala",
    "Como se chama a passagem de líquido para sólido?|Solidificação|Fusão|Condensação|Sublimação",
    "Qual sentido permite perceber sons?|Audição|Visão|Olfato|Paladar",
    "Qual satélite natural orbita a Terra?|Lua|Fobos|Europa|Titã",
    "Qual material é atraído por um ímã comum?|Ferro|Madeira|Vidro|Papel",
    "Quantas pernas tem um inseto adulto típico?|Seis|Quatro|Oito|Dez",
    "Qual destes é um réptil?|Jacaré|Sapo|Baleia|Pinguim",
    "Qual substância tem fórmula H₂O?|Água|Sal de cozinha|Gás carbônico|Amônia",
    "Qual órgão humano é associado principalmente à visão?|Olho|Ouvido|Nariz|Língua",
    "O que a fotossíntese usa como fonte de energia?|Luz|Som|Vento|Gravidade",
    "Qual destes seres é um fungo?|Cogumelo|Samambaia|Musgo|Roseira",
    "Como se chama o movimento da Terra ao redor do Sol?|Translação|Rotação|Vibração|Reflexão",
    "Qual instrumento mede temperatura?|Termômetro|Barômetro|Bússola|Régua",
    "Qual grupo inclui sapos e salamandras?|Anfíbios|Aves|Mamíferos|Peixes",
    "Como se chama a água no estado gasoso?|Vapor de água|Gelo|Orvalho|Neve",
    "Qual estrutura protege o cérebro humano?|Crânio|Costela|Fêmur|Bacia",
    "Qual destes é uma fonte renovável de energia?|Vento|Carvão mineral|Petróleo|Gás natural",
    "Qual planeta tem anéis muito visíveis em telescópios?|Saturno|Mercúrio|Marte|Vênus",
    "Que força mantém objetos atraídos pela Terra?|Gravidade|Atrito|Empuxo|Força elástica",
  ] },
  { category: "science", difficulty: "medium", rows: [
    "Qual organela é associada à produção de ATP na respiração aeróbica?|Mitocôndria|Lisossomo|Complexo de Golgi|Centríolo",
    "Qual é o gás mais abundante na atmosfera terrestre seca?|Nitrogênio|Oxigênio|Gás carbônico|Hidrogênio",
    "Qual unidade do SI mede força?|Newton|Joule|Watt|Pascal",
    "Qual partícula do átomo tem carga negativa?|Elétron|Próton|Nêutron|Fóton",
    "Qual é o símbolo químico do sódio?|Na|S|Si|Sn",
    "Que processo transforma vapor de água em líquido?|Condensação|Fusão|Sublimação|Solidificação",
    "Qual estrutura celular contém a maior parte do DNA em células humanas?|Núcleo|Membrana plasmática|Lisossomo|Ribossomo",
    "Qual molécula carrega a informação genética de forma principal nos seres celulares?|DNA|ATP|Glicose|Colesterol",
    "Que células do sangue transportam a maior parte do oxigênio?|Hemácias|Plaquetas|Neurônios|Osteócitos",
    "Qual camada terrestre fica entre crosta e núcleo?|Manto|Troposfera|Estratosfera|Ionosfera",
    "Qual é a unidade do SI de corrente elétrica?|Ampere|Volt|Ohm|Watt",
    "Qual fenômeno desvia a luz ao passar entre meios transparentes diferentes?|Refração|Evaporação|Condução|Magnetização",
    "Qual planeta é o maior do Sistema Solar?|Júpiter|Saturno|Urano|Netuno",
    "Que relação ecológica beneficia ambos os participantes?|Mutualismo|Parasitismo|Predação|Competição",
    "Qual tipo de energia está associado ao movimento?|Cinética|Química|Nuclear|Potencial gravitacional",
    "Qual unidade do SI mede energia?|Joule|Newton|Ampere|Kelvin",
    "Qual é o símbolo químico do ferro?|Fe|F|Fr|Fm",
    "Que divisão celular normalmente produz dois núcleos geneticamente semelhantes?|Mitose|Meiose|Fecundação|Tradução",
    "Qual é a função principal dos ribossomos?|Produzir proteínas|Armazenar água|Digerir lipídios|Transportar oxigênio",
    "Como se chama um animal que mantém temperatura interna relativamente estável por metabolismo?|Endotérmico|Ectotérmico|Autótrofo|Decompositor",
    "Qual onda eletromagnética tem frequência maior que a luz visível?|Ultravioleta|Rádio|Micro-ondas|Infravermelho",
    "Qual grandeza mede massa por unidade de volume?|Densidade|Pressão|Potência|Velocidade",
    "Qual processo separa sólidos insolúveis de um líquido com um filtro?|Filtração|Destilação|Fusão|Condensação",
    "Qual animal passa por metamorfose completa com fase de pupa?|Borboleta|Gafanhoto|Barata|Libélula",
    "Qual órgão filtra o sangue e participa da formação da urina?|Rim|Baço|Estômago|Pâncreas",
  ] },
  { category: "science", difficulty: "hard", rows: [
    "Qual ligação envolve compartilhamento de pares de elétrons?|Covalente|Iônica|Metálica|Ligação gravitacional",
    "Qual princípio relaciona empuxo ao peso do fluido deslocado?|Princípio de Arquimedes|Princípio de Pascal|Lei de Ohm|Lei de Hooke",
    "Isótopos de um elemento diferem em qual quantidade?|Número de nêutrons|Número de prótons|Número atômico|Carga do próton",
    "Qual base do RNA substitui a timina do DNA?|Uracila|Adenina|Citosina|Guanina",
    "Qual unidade do SI mede pressão?|Pascal|Watt|Tesla|Coulomb",
    "Que fenômeno altera a frequência percebida quando fonte e observador se movem relativamente?|Efeito Doppler|Efeito Joule|Osmose|Difração estática",
    "Qual escala de temperatura tem zero no zero absoluto?|Kelvin|Celsius|Fahrenheit|Escala de Beaufort",
    "Qual grandeza é conservada em uma colisão de sistema isolado?|Quantidade de movimento|Velocidade de cada corpo|Energia cinética de cada corpo|Temperatura de cada corpo",
    "Qual é a unidade do SI de resistência elétrica?|Ohm|Volt|Ampere|Farad",
    "Que lei relaciona F = m × a?|Segunda lei de Newton|Primeira lei de Newton|Terceira lei de Newton|Lei de Coulomb",
    "Qual processo copia informação do DNA para RNA?|Transcrição|Tradução|Replicação proteica|Fermentação",
    "Em uma célula eucariótica, onde ocorre principalmente a glicólise?|Citosol|Núcleo|Lisossomo|Membrana interna mitocondrial",
    "Qual característica define um catalisador químico?|Reduz a energia de ativação|Aumenta sempre a temperatura|É consumido por completo|Altera a massa total do sistema",
    "Qual é a unidade do SI de frequência?|Hertz|Joule|Weber|Henry",
    "Qual processo transporta água através de uma membrana semipermeável?|Osmose|Tradução|Fissão|Ionização",
    "Uma solução aquosa com pH 3, a 25 °C, é classificada como quê?|Ácida|Neutra|Básica|Sem íons",
    "Qual partícula determina o número atômico de um elemento?|Próton|Nêutron|Elétron de valência|Fóton",
    "Que lei elétrica é expressa por V = R × I?|Lei de Ohm|Lei de Faraday|Lei de Hooke|Lei de Boyle",
    "Qual fenômeno permite ondas contornarem obstáculos?|Difração|Condensação|Sublimação|Eletrólise",
    "Qual molécula é usada como portadora imediata de energia celular?|ATP|DNA|Celulose|Hemoglobina",
    "Qual processo libera energia na união de núcleos leves?|Fusão nuclear|Fissão nuclear|Evaporação|Cristalização",
    "Qual é a unidade do SI de carga elétrica?|Coulomb|Tesla|Kelvin|Candela",
    "Qual tipo de lente convergente é mais espesso no centro que nas bordas, no ar?|Convexa|Côncava|Plana|Cilíndrica divergente",
    "Qual propriedade caracteriza uma onda transversal?|Oscilação perpendicular à propagação|Oscilação sempre paralela à propagação|Ausência de frequência|Transporte obrigatório de matéria",
    "Qual lei diz que pressão de gás ideal é inversamente proporcional ao volume a temperatura constante?|Lei de Boyle|Lei de Charles|Lei de Ohm|Lei de Snell",
  ] },
  { category: "math", difficulty: "easy", rows: [
    "Quantos lados tem um triângulo?|3|4|5|6",
    "Quanto é 7 + 8?|15|14|16|17",
    "Quanto é 9 × 6?|54|45|63|56",
    "Qual é a metade de 50?|25|20|30|15",
    "Qual é o dobro de 18?|36|28|32|38",
    "Quantos centímetros há em um metro?|100|10|1000|50",
    "Qual destes números é par?|24|13|17|21",
    "Quanto é 60 dividido por 5?|12|10|15|20",
    "Qual figura tem quatro lados iguais e quatro ângulos retos?|Quadrado|Triângulo|Pentágono|Círculo",
    "Quanto é 20% de 100?|20|10|25|50",
    "Qual é o sucessor de 99?|100|98|101|90",
    "Quantos minutos há em uma hora?|60|30|90|100",
    "Qual é a soma dos ângulos internos de um triângulo plano?|180°|90°|270°|360°",
    "Quanto vale 3²?|9|6|8|12",
    "Qual fração representa metade?|1/2|1/3|2/3|1/4",
    "Qual destes números é negativo?|-5|0|5|10",
    "Quanto é 100 - 37?|63|67|73|53",
    "Quantos lados tem um hexágono?|6|5|7|8",
    "Qual símbolo indica maior que?|>|<|=|+",
    "Quanto é 0 multiplicado por 85?|0|85|1|850",
    "Qual é o triplo de 7?|21|14|28|24",
    "Qual é a raiz quadrada positiva de 25?|5|4|6|10",
    "Quantas unidades há em uma dúzia?|12|10|15|20",
    "Qual decimal é igual a 1/4?|0,25|0,5|0,75|0,125",
    "Qual é o perímetro de um quadrado com lado 3 cm?|12 cm|9 cm|6 cm|3 cm",
  ] },
  { category: "math", difficulty: "medium", rows: [
    "Qual é a média aritmética de 4, 6 e 8?|6|5|7|8",
    "Qual é a área de um retângulo de 5 cm por 8 cm?|40 cm²|26 cm²|13 cm²|80 cm²",
    "Se 2x + 3 = 11, quanto vale x?|4|3|5|7",
    "Qual é o mínimo múltiplo comum de 6 e 8?|24|12|48|14",
    "Qual é o máximo divisor comum de 18 e 24?|6|3|9|12",
    "Qual é a probabilidade de sair 6 em um dado justo de seis faces?|1/6|1/3|1/2|5/6",
    "Quanto é 2/3 + 1/6?|5/6|3/9|1/2|1",
    "Qual destes números é primo?|29|21|27|35",
    "Qual é a mediana de 2, 4, 9, 10 e 15?|9|4|10|8",
    "Qual é o volume de um cubo com aresta de 3 cm?|27 cm³|9 cm³|18 cm³|12 cm³",
    "Qual é a soma dos ângulos internos de um quadrilátero plano simples?|360°|180°|270°|540°",
    "Em um triângulo retângulo com catetos 3 e 4, quanto mede a hipotenusa?|5|6|7|8",
    "Quanto vale 2 elevado a 5?|32|10|25|64",
    "Um produto de R$ 80 recebe desconto de 25%. Qual é o preço final?|R$ 60|R$ 55|R$ 65|R$ 70",
    "Qual número corresponde a 15% de 200?|30|15|20|40",
    "Qual é o inverso multiplicativo de 5?|1/5|-5|5|0",
    "Qual é a moda de 1, 2, 2, 3 e 4?|2|1|3|4",
    "Quanto é (-3) × (-4)?|12|-12|-7|7",
    "Se uma escala é 1:100, 2 cm no mapa representam quantos metros?|2 m|20 m|0,2 m|200 m",
    "Qual é a área de um triângulo de base 10 e altura 6?|30|60|16|20",
    "Qual expressão representa a circunferência de um círculo de raio r?|2πr|πr²|πr|4πr²",
    "Qual é o valor absoluto de -8?|8|-8|0|1/8",
    "Quanto é 0,6 dividido por 0,2?|3|0,3|0,12|30",
    "Se 5 cadernos custam R$ 40, quanto custam 3 ao mesmo preço unitário?|R$ 24|R$ 20|R$ 30|R$ 15",
    "Qual é o próximo termo de 3, 6, 12, 24, dobrando a cada passo?|48|36|42|60",
  ] },
  { category: "math", difficulty: "hard", rows: [
    "Qual é log₂(32)?|5|4|6|8",
    "Qual é a derivada de x² em relação a x?|2x|x|x³|2",
    "Quanto vale a integral definida de 2x entre 0 e 1?|1|2|0|1/2",
    "Qual é o determinante da matriz com linhas (1, 2) e (3, 4)?|-2|2|10|-10",
    "Quantas combinações de 2 elementos podem ser feitas a partir de 5 distintos?|10|20|25|5",
    "Qual é a probabilidade de duas caras ao lançar duas moedas justas independentes?|1/4|1/2|3/4|1/8",
    "Qual é a soma das raízes de x² - 5x + 6 = 0?|5|6|-5|-6",
    "Quanto vale i², com i a unidade imaginária?|-1|1|0|i",
    "Qual é o limite de (x² - 1)/(x - 1) quando x tende a 1?|2|1|0|Não existe",
    "Qual é a soma dos primeiros 10 inteiros positivos?|55|50|45|100",
    "Qual é sen(30°)?|1/2|√3/2|1|0",
    "Qual é cos(60°)?|1/2|√2/2|√3/2|0",
    "Qual é o resto da divisão de 17 por 5?|2|3|1|4",
    "Quantas permutações distintas existem de 4 objetos diferentes?|24|16|12|8",
    "Qual é a área de um círculo de raio 3?|9π|6π|3π|12π",
    "Qual é a soma dos ângulos internos de um pentágono plano simples?|540°|360°|720°|900°",
    "Qual é a inclinação da reta y = 3x - 2?|3|-2|2|-3",
    "Qual é a distância entre (0, 0) e (6, 8) no plano cartesiano?|10|14|8|12",
    "Qual é o valor de 5! ?|120|25|60|100",
    "Qual é a soma infinita de 1 + 1/2 + 1/4 + 1/8 + … ?|2|1|3|Infinita",
    "Qual destes números é irracional?|√2|1/2|0,25|3",
    "Qual é a variância populacional dos valores 1 e 3?|1|2|0|4",
    "Qual é o produto escalar de (1, 2) e (3, 4)?|11|7|10|14",
    "Qual é a solução de 3 elevado a x = 81?|4|3|5|6",
    "Qual é a soma de uma progressão aritmética de cinco termos, primeiro 2 e último 10?|30|25|20|40",
  ] },
];
export const quizQuestions: readonly QuizQuestion[] = groups.flatMap(({ category, difficulty, rows }) => rows.map((row, index) => {
  const [prompt, ...answers] = row.split("|");
  return questionSchema.parse({ id: `${category}-${difficulty}-${index + 1}`, category, difficulty, prompt, answers, correctIndex: 0 });
}));
