import assert from "node:assert/strict";
import test from "node:test";
import { spawn } from "node:child_process";
import fs from "node:fs";
import net from "node:net";
import os from "node:os";
import path from "node:path";
import { io, type Socket } from "socket.io-client";
import type { User } from "@lumio/shared";

test("M2 REST and realtime: House isolation, shared idempotent favorites, collections and reconnect", { timeout: 90_000 }, async (context) => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "lumio-m2-"));
  const port = await new Promise<number>((resolve) => { const server = net.createServer(); server.listen(0, "127.0.0.1", () => { const port = (server.address() as net.AddressInfo).port; server.close(() => resolve(port)); }); });
  const outbox = path.join(directory, "mail.jsonl"), origin = "http://127.0.0.1:5173", api = `http://127.0.0.1:${port}`;
  const child = spawn(process.execPath, ["--import", "tsx", "src/index.ts"], { env: { ...process.env, PORT: String(port), NODE_ENV: "development", PERSISTENCE_MODE: "file", AUTH_STORE_FILE: path.join(directory, "auth.json"), EMAIL_PROVIDER: "dev-file", EMAIL_DEV_OUTBOX_FILE: outbox, APP_PUBLIC_URL: origin, CLIENT_ORIGIN: origin, GOOGLE_CLIENT_ID: "", GOOGLE_CLIENT_SECRET: "", GOOGLE_TOKEN_ENCRYPTION_KEY: "", YOUTUBE_API_KEY: "" }, stdio: "ignore" });
  const sockets: Socket[] = [];
  context.after(async () => { sockets.forEach((socket) => socket.disconnect()); child.kill(); await Promise.race([new Promise((resolve) => child.once("exit", resolve)), new Promise((resolve) => setTimeout(resolve, 2000))]); fs.rmSync(directory, { recursive: true, force: true }); });
  const until = async (predicate: () => boolean | Promise<boolean>) => { for (let index = 0; index < 150; index++) { if (await predicate()) return; await new Promise((resolve) => setTimeout(resolve, 100)); } throw new Error("M2 integration timed out"); };
  await until(async () => { try { return (await fetch(`${api}/api/health`)).ok; } catch { return false; } });
  const request = (route: string, token?: string, body?: unknown, method = "POST") => fetch(api + route, { method, headers: { ...(token ? { Authorization: `Bearer ${token}` } : {}), ...(body ? { "Content-Type": "application/json" } : {}) }, body: body ? JSON.stringify(body) : undefined });
  const sessions: Array<{ token: string; user: User }> = [];
  for (const displayName of ["Ana", "Bia", "Caio"]) {
    const email = `${displayName.toLowerCase()}@example.test`, password = "m2-local-test-123";
    assert.equal((await request("/api/auth/signup", undefined, { displayName, email, password })).status, 201);
    const link = JSON.parse(fs.readFileSync(outbox, "utf8").trim().split("\n").at(-1)!).text.match(/https?:\/\/\S+/)[0];
    assert.equal((await request("/api/auth/verification/confirm", undefined, { token: new URL(link).hash.slice(7) })).status, 204);
    sessions.push(await (await request("/api/auth/login", undefined, { email, password })).json());
  }
  const x = (await (await request("/api/houses", sessions[0].token, { name: "Casa X" })).json()).house;
  const y = (await (await request("/api/houses", sessions[2].token, { name: "Casa Y" })).json()).house;
  const invite = (await (await request(`/api/houses/${x.id}/invites`, sessions[0].token, { maxUses: 2, expiresInHours: 1 })).json()).invite;
  assert.equal((await request(`/api/invites/${invite.code}/accept`, sessions[1].token)).status, 200);
  const observed = [0, 0, 0];
  const connect = async (index: number, roomId: string) => {
    const socket = io(api, { transports: ["websocket"], auth: { token: sessions[index].token }, extraHeaders: { Origin: origin } });
    sockets.push(socket);
    socket.on("media-hub:update", () => { observed[index]++; });
    await until(() => socket.connected);
    const joined = new Promise<void>((resolve) => socket.once("room:snapshot", () => resolve()));
    socket.emit("room:join", { roomId, user: sessions[index].user });
    await joined;
    return socket;
  };
  await connect(0, x.primaryRoomId);
  let b = await connect(1, x.primaryRoomId);
  await connect(2, y.primaryRoomId);
  const route = `/api/media-hub/${x.primaryRoomId}`;
  const media = { id: "youtube:abcdefghijk", provider: "youtube", providerMediaId: "abcdefghijk", type: "video", title: "Shared video", thumbnail: "https://evil.example/a", metadata: { token: "secret" } };
  const favorite = (index: number, method: string) => request(`${route}/favorite`, sessions[index].token, { item: media }, method);
  assert.equal((await favorite(0, "PUT")).status, 200);
  await until(() => observed[1] === 1);
  assert.equal(observed[2], 0, "different House socket receives no library event");
  assert.equal((await favorite(1, "PUT")).status, 200);
  assert.equal((await (await request(route, sessions[1].token, undefined, "GET")).json()).favorites.length, 1);
  assert.equal((await request(route, sessions[2].token, undefined, "GET")).status, 403);
  assert.equal((await request(`${route}/history`, sessions[2].token, undefined, "GET")).status, 403);
  const library = (await (await request(route, sessions[1].token, undefined, "GET")).json()).library;
  assert.equal(library[0].thumbnail, "https://i.ytimg.com/vi/abcdefghijk/hqdefault.jpg");
  assert.equal(library[0].metadata?.token, undefined);
  b.disconnect();
  assert.equal((await favorite(0, "DELETE")).status, 200);
  assert.equal((await favorite(0, "DELETE")).status, 200);
  const concurrentSaves = await Promise.all([favorite(0, "PUT"), favorite(1, "PUT")]);
  assert.deepEqual(concurrentSaves.map((result) => result.status), [200, 200]);
  assert.equal((await (await request(route, sessions[0].token, undefined, "GET")).json()).favorites.length, 1);
  const concurrentRemovals = await Promise.all([favorite(0, "DELETE"), favorite(1, "DELETE")]);
  assert.deepEqual(concurrentRemovals.map((result) => result.status), [200, 200]);
  b = await connect(1, x.primaryRoomId);
  assert.equal((await (await request(route, sessions[1].token, undefined, "GET")).json()).favorites.length, 0);
  const created = await request(`${route}/playlists`, sessions[1].token, { name: "Shared" });
  assert.equal(created.status, 201);
  const collection = (await created.json()).playlist;
  await until(() => observed[0] >= 3);
  assert.equal((await request(`${route}/playlists/${collection.id}`, sessions[2].token, undefined, "GET")).status, 403);
  const concurrentAdds = await Promise.all([0, 1].map((index) => request(`${route}/playlists/${collection.id}/items`, sessions[index].token, { item: media })));
  assert.deepEqual(concurrentAdds.map((result) => result.status).sort(), [200, 201]);
  const detail = (await (await request(`${route}/playlists/${collection.id}`, sessions[1].token, undefined, "GET")).json()).playlist;
  assert.equal(detail.items.length, 1);
  assert.equal((await request(`${route}/playlists/${collection.id}`, sessions[0].token, { name: "A", expectedUpdatedAt: detail.updatedAt }, "PATCH")).status, 200);
  assert.equal((await request(`${route}/playlists/${collection.id}`, sessions[1].token, { name: "B", expectedUpdatedAt: detail.updatedAt }, "PATCH")).status, 409);
  assert.equal((await request(`${route}/playlists/${collection.id}`, sessions[1].token, undefined, "DELETE")).status, 403);
  assert.equal((await request(`${route}/playlists/${collection.id}`, sessions[0].token, undefined, "DELETE")).status, 204);
  assert.equal((await request(`${route}/playlists/${collection.id}`, sessions[1].token, undefined, "GET")).status, 404);
  assert.equal(observed[2], 0);
  assert.equal((await (await request(`/api/media-hub/${y.primaryRoomId}`, sessions[2].token, undefined, "GET")).json()).favorites.length, 0);
});
