import { useEffect, useState, type FormEvent } from "react";
import { ArrowRight, Headphones, Link2, MessageCircle, MonitorUp, Play, Plus, Users, X } from "lucide-react";
import type { HouseDetails, HouseSummary, User } from "@lumio/shared";
import { Avatar } from "./Avatar";

type Navigate = (path: string) => void;

function Wordmark() { return <span className="entry-wordmark"><span className="brand-symbol">L</span><strong>Lumio</strong></span>; }

export function BootstrapPage({ error, onRetry }: { error?: string; onRetry: () => void }) {
  return <main className="entry-bootstrap"><Wordmark />{error ? <><p>{error}</p><button onClick={onRetry}>Tentar novamente</button></> : <span className="entry-loader" aria-label="Carregando" />}</main>;
}

export function LandingPage({ navigate }: { navigate: Navigate }) {
  useEffect(() => { document.title = "Lumio — assista e ouça junto"; }, []);
  return <main className="landing-page landing-v2"><header className="entry-header"><Wordmark /><nav aria-label="Acesso"><button onClick={() => navigate("/login")}>Entrar</button><button className="entry-primary compact" onClick={() => navigate("/register")}>Criar conta</button></nav></header><section className="landing-hero"><div className="hero-signal"><span /> Uma Party. Todo mundo no mesmo momento.</div><p className="eyebrow">O lugar de vocês</p><h1>Fiquem juntos,<br /><span>mesmo de longe.</span></h1><p>Assista, ouça e converse no mesmo lugar. O Lumio mantém a mídia, a fila e as pessoas no mesmo ritmo.</p><div className="hero-actions"><button className="entry-primary" onClick={() => navigate("/register")}>Criar minha Casa <ArrowRight /></button><button onClick={() => navigate("/login")}>Entrar</button></div><div className="hero-proof"><span>Player Lumio</span><span>Party sincronizada</span><span>Call integrada</span></div></section><ProductPreview /><section className="landing-capabilities" aria-labelledby="capabilities-title"><header><p className="eyebrow">Mais presença, menos distância</p><h2 id="capabilities-title">A noite acontece em um só lugar.</h2></header><div><article><span>ASSISTA</span><h3>Um player que é do Lumio</h3><p>Controles consistentes sobre o mecanismo oficial do YouTube, com sincronização da Party.</p></article><article><span>OUÇA</span><h3>A fila é de todo mundo</h3><p>Descubram músicas, montem playlists e escolham juntos o que vem a seguir.</p></article><article><span>CONVERSE</span><h3>As pessoas continuam por perto</h3><p>Call, chat, reações e compartilhamento de tela sem desmontar a experiência.</p></article></div></section><section className="landing-final"><p className="eyebrow">Sua próxima noite</p><h2>Abre a Casa.<br />O resto vocês decidem.</h2><button className="entry-primary" onClick={() => navigate("/register")}>Começar no Lumio <ArrowRight /></button></section><footer className="entry-footer"><Wordmark /><span>Feito para ficar por perto.</span><small>© {new Date().getFullYear()} Lumio</small></footer></main>;
}

function ProductPreview() {
  return <section className="product-preview landing-player-preview" aria-label="Prévia real da Party Lumio"><div className="preview-chrome"><Wordmark /><span>Casa da turma</span><div><Users /> 4</div></div><div className="preview-stage"><div className="preview-video"><div className="preview-ambient" /><span className="preview-play"><Play fill="currentColor" /></span><p>Uma noite, todo mundo junto.</p><small>PLAYER LUMIO · YOUTUBE</small><div className="preview-player-controls"><span className="preview-progress"><i /></span><div><Play fill="currentColor" /><small>01:42 / 04:21</small><span>🔊</span><span>⛶</span></div></div></div><aside><strong>Na Party</strong>{["Duda", "Maya", "João"].map((name, index) => <div key={name}><span className={`preview-avatar color-${index}`}>{name[0]}</span><p>{name}<small>{index === 0 ? "Falando" : "Assistindo"}</small></p></div>)}</aside></div><div className="preview-dock"><Headphones /><MonitorUp /><MessageCircle /><button><Plus /> Adicionar mídia</button></div></section>;
}

export function AuthPage({ mode, error, onSubmit, navigate }: { mode: "login" | "register"; error: string; onSubmit: (data: { displayName: string; email: string; password: string }) => Promise<void>; navigate: Navigate }) {
  const [displayName, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState(""); const [localError, setLocalError] = useState(""); const [busy, setBusy] = useState(false);
  useEffect(() => { document.title = `${mode === "login" ? "Entrar" : "Criar conta"} — Lumio`; }, [mode]);
  const submit = async (event: FormEvent) => { event.preventDefault(); setLocalError(""); if (mode === "register" && displayName.trim().length < 2) return setLocalError("Digite seu nome."); if (!/^\S+@\S+\.\S+$/.test(email)) return setLocalError("Digite um e-mail válido."); if (password.length < 8) return setLocalError("A senha precisa ter pelo menos 8 caracteres."); if (mode === "register" && password !== confirmation) return setLocalError("As senhas não coincidem."); setBusy(true); await onSubmit({ displayName, email, password }); setBusy(false); };
  const next = new URLSearchParams(window.location.search).get("next"); const otherPath = `${mode === "login" ? "/register" : "/login"}${next ? `?next=${encodeURIComponent(next)}` : ""}`;
  return <main className="auth-page"><button className="auth-wordmark" onClick={() => navigate("/")}><Wordmark /></button><section className="auth-panel"><header><p className="eyebrow">{mode === "login" ? "Bem-vindo de volta" : "Comece por aqui"}</p><h1>{mode === "login" ? "Entrar" : "Criar sua conta"}</h1><p>{mode === "login" ? "Sua Casa está esperando." : "Depois, você cria uma Casa ou entra por convite."}</p></header><form onSubmit={submit} noValidate>{mode === "register" ? <label htmlFor="auth-name">Nome<input id="auth-name" value={displayName} onChange={(e) => setName(e.target.value)} autoComplete="name" /></label> : null}<label htmlFor="auth-email">E-mail<input id="auth-email" type="email" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="email" inputMode="email" /></label><label htmlFor="auth-password">Senha<input id="auth-password" type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete={mode === "login" ? "current-password" : "new-password"} /></label>{mode === "register" ? <label htmlFor="auth-confirmation">Confirmar senha<input id="auth-confirmation" type="password" value={confirmation} onChange={(e) => setConfirmation(e.target.value)} autoComplete="new-password" /></label> : null}<p className="form-error" role="alert" aria-live="polite">{localError || error}</p><button className="entry-primary" disabled={busy}>{busy ? mode === "login" ? "Entrando…" : "Criando…" : mode === "login" ? "Entrar" : "Criar conta"}</button></form><p className="auth-alternate">{mode === "login" ? "Ainda não tem conta?" : "Já tem uma conta?"} <button onClick={() => navigate(otherPath)}>{mode === "login" ? "Criar conta" : "Entrar"}</button></p></section></main>;
}

export function HomePage({ user, houses, error, onRetry, onOpenHouse, onCreate, onInvite, onLogout }: { user: User; houses: HouseSummary[]; error?: string; onRetry: () => void; onOpenHouse: (house: HouseSummary) => void; onCreate: (name: string) => Promise<void>; onInvite: () => void; onLogout: () => void }) {
  const [creating, setCreating] = useState(false); const [name, setName] = useState(""); const [busy, setBusy] = useState(false); const hour = new Date().getHours(); const greeting = hour < 12 ? "Bom dia" : hour < 18 ? "Boa tarde" : "Boa noite";
  useEffect(() => { document.title = "Suas Casas — Lumio"; }, []);
  const create = async (event: FormEvent) => { event.preventDefault(); if (name.trim().length < 2) return; setBusy(true); await onCreate(name); setBusy(false); };
  return <main className="home-page"><header className="entry-header"><Wordmark /><div className="home-account"><Avatar name={user.displayName} src={user.avatar} color={user.color} /><div><strong>{user.displayName}</strong><button onClick={onLogout}>Sair</button></div></div></header><section className="home-content"><header><p>{greeting}, {user.displayName.split(" ")[0]}.</p><h1>{houses.length ? "Suas Casas" : "Sua primeira Casa começa aqui."}</h1></header>{error ? <div className="home-error"><p>{error}</p><button onClick={onRetry}>Tentar novamente</button></div> : houses.length ? <div className="house-grid">{houses.map((house) => <button className="house-card" key={house.id} onClick={() => onOpenHouse(house)}><span className="house-card-avatar">{house.initials}</span><div><h2>{house.name}</h2><p className={house.onlineCount ? "is-active" : ""}>{house.onlineCount ? `● ${house.onlineCount} ${house.onlineCount === 1 ? "pessoa por aqui" : "pessoas por aqui"}` : "Ninguém por aqui"}</p>{house.nowPlaying ? <span><small>Tocando agora</small>{house.nowPlaying.title}</span> : <span><small>Party</small>Nada tocando agora</span>}</div><ArrowRight /></button>)}</div> : <div className="home-empty"><span className="home-empty-mark">L</span><p>Crie um espaço para assistir, ouvir e conversar com sua galera.</p><button className="entry-primary" onClick={() => setCreating(true)}><Plus /> Criar Casa</button><button onClick={onInvite}><Link2 /> Entrar com convite</button></div>}{houses.length ? <button className="create-house-inline" onClick={() => setCreating(true)}><Plus /> Criar outra Casa</button> : null}</section>{creating ? <div className="dialog-backdrop"><section className="dialog create-house-dialog" role="dialog" aria-modal="true" aria-labelledby="create-house-title"><header><div><h2 id="create-house-title">Criar Casa</h2><p>Um nome basta. O resto vocês decidem juntos.</p></div><button className="icon-button" onClick={() => setCreating(false)} aria-label="Fechar"><X /></button></header><form onSubmit={create}><label htmlFor="house-name">Nome da Casa<input id="house-name" value={name} onChange={(e) => setName(e.target.value)} autoFocus maxLength={48} placeholder="Noite dos amigos" /></label><button className="entry-primary" disabled={busy || name.trim().length < 2}>{busy ? "Criando…" : "Criar e entrar"}</button></form></section></div> : null}</main>;
}

interface InviteState { status: "LOADING" | "VALID" | "INVALID" | "EXPIRED" | "REVOKED" | "LIMIT_REACHED" | "NETWORK"; houseName?: string; houseId?: string; invitedBy?: string; onlineCount?: number; isMember?: boolean }
export function InvitePage({ apiUrl, token, session, navigate, onAccepted }: { apiUrl: string; token: string; session: { token: string } | null; navigate: Navigate; onAccepted: (houseId: string) => Promise<void> }) {
  const [state, setState] = useState<InviteState>({ status: "LOADING" }); const [busy, setBusy] = useState(false);
  const load = () => { setState({ status: "LOADING" }); fetch(`${apiUrl}/api/invites/${encodeURIComponent(token)}`, { headers: session ? { Authorization: `Bearer ${session.token}` } : undefined }).then(async (response) => setState(await response.json())).catch(() => setState({ status: "NETWORK" })); };
  useEffect(() => { document.title = "Convite — Lumio"; }, []);
  useEffect(load, [token, session?.token]);
  const accept = async () => { if (!session) return; if (state.isMember && state.houseId) return onAccepted(state.houseId); setBusy(true); const response = await fetch(`${apiUrl}/api/invites/${encodeURIComponent(token)}/accept`, { method: "POST", headers: { Authorization: `Bearer ${session.token}` } }); const data = await response.json(); setBusy(false); if (response.ok) await onAccepted(data.houseId); else setState({ status: data.status ?? "INVALID" }); };
  const next = `/invite/${token}`;
  return <main className="invite-page"><button onClick={() => navigate(session ? "/app" : "/")}><Wordmark /></button><section>{state.status === "LOADING" ? <span className="entry-loader" aria-label="Carregando convite" /> : state.status === "NETWORK" ? <><h1>Não foi possível abrir o convite.</h1><p>Confira sua conexão e tente novamente.</p><button className="entry-primary" onClick={load}>Tentar novamente</button></> : state.status !== "VALID" ? <><p className="eyebrow">Convite indisponível</p><h1>Este convite não está mais disponível.</h1><p>Ele pode ter expirado, sido revogado ou atingido o limite de usos.</p><button className="entry-primary" onClick={() => navigate(session ? "/app" : "/")}>Voltar ao Lumio</button></> : <><p className="eyebrow">Você foi convidado para</p><h1>{state.houseName}</h1><p>{state.invitedBy ? `${state.invitedBy} convidou você.` : "Tem gente esperando por você."}</p>{state.onlineCount ? <small>● {state.onlineCount} {state.onlineCount === 1 ? "pessoa está" : "pessoas estão"} por aqui</small> : null}{session ? <button className="entry-primary" disabled={busy} onClick={() => void accept()}>{busy ? "Entrando…" : state.isMember ? "Abrir Party" : "Entrar na Casa"}</button> : <div className="invite-auth-actions"><button className="entry-primary" onClick={() => navigate(`/login?next=${encodeURIComponent(next)}`)}>Entrar</button><button onClick={() => navigate(`/register?next=${encodeURIComponent(next)}`)}>Criar conta</button></div>}</>}</section></main>;
}
